apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlrun

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - clickhouse.yaml
  - minio.yaml
  - redis.yaml
  - api.yaml
  - ui.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "0.1.0"
